// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/apkpure.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApkPureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ApkPureResponseData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ApkPureResponse) Reset() {
	*x = ApkPureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureResponse) ProtoMessage() {}

func (x *ApkPureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureResponse.ProtoReflect.Descriptor instead.
func (*ApkPureResponse) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{0}
}

func (x *ApkPureResponse) GetData() *ApkPureResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApkPureResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *ApkPureResponseDetail `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *ApkPureResponseData) Reset() {
	*x = ApkPureResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureResponseData) ProtoMessage() {}

func (x *ApkPureResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureResponseData.ProtoReflect.Descriptor instead.
func (*ApkPureResponseData) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{1}
}

func (x *ApkPureResponseData) GetDetail() *ApkPureResponseDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ApkPureResponseDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationVersion []*ApkPureApplicationVersion `protobuf:"bytes,2,rep,name=applicationVersion,proto3" json:"applicationVersion,omitempty"`
}

func (x *ApkPureResponseDetail) Reset() {
	*x = ApkPureResponseDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureResponseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureResponseDetail) ProtoMessage() {}

func (x *ApkPureResponseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureResponseDetail.ProtoReflect.Descriptor instead.
func (*ApkPureResponseDetail) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{2}
}

func (x *ApkPureResponseDetail) GetApplicationVersion() []*ApkPureApplicationVersion {
	if x != nil {
		return x.ApplicationVersion
	}
	return nil
}

type ApkPureApplicationVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType string                          `protobuf:"bytes,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Result      *ApkPureApplicationSearchResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ApkPureApplicationVersion) Reset() {
	*x = ApkPureApplicationVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureApplicationVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureApplicationVersion) ProtoMessage() {}

func (x *ApkPureApplicationVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureApplicationVersion.ProtoReflect.Descriptor instead.
func (*ApkPureApplicationVersion) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{3}
}

func (x *ApkPureApplicationVersion) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ApkPureApplicationVersion) GetResult() *ApkPureApplicationSearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ApkPureApplicationSearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ApkPureApplicationVersionData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ApkPureApplicationSearchResult) Reset() {
	*x = ApkPureApplicationSearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureApplicationSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureApplicationSearchResult) ProtoMessage() {}

func (x *ApkPureApplicationSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureApplicationSearchResult.ProtoReflect.Descriptor instead.
func (*ApkPureApplicationSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{4}
}

func (x *ApkPureApplicationSearchResult) GetData() *ApkPureApplicationVersionData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApkPureApplicationVersionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName  string                      `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Package      string                      `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	MinorVersion string                      `protobuf:"bytes,5,opt,name=minorVersion,proto3" json:"minorVersion,omitempty"`
	Version      string                      `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Hash         string                      `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	Description  string                      `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	PatchNotes   string                      `protobuf:"bytes,11,opt,name=patchNotes,proto3" json:"patchNotes,omitempty"`
	Status       string                      `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Developer    string                      `protobuf:"bytes,13,opt,name=developer,proto3" json:"developer,omitempty"`
	Download     *ApkPureApplicationDownload `protobuf:"bytes,24,opt,name=download,proto3" json:"download,omitempty"`
}

func (x *ApkPureApplicationVersionData) Reset() {
	*x = ApkPureApplicationVersionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureApplicationVersionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureApplicationVersionData) ProtoMessage() {}

func (x *ApkPureApplicationVersionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureApplicationVersionData.ProtoReflect.Descriptor instead.
func (*ApkPureApplicationVersionData) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{5}
}

func (x *ApkPureApplicationVersionData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetMinorVersion() string {
	if x != nil {
		return x.MinorVersion
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetPatchNotes() string {
	if x != nil {
		return x.PatchNotes
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *ApkPureApplicationVersionData) GetDownload() *ApkPureApplicationDownload {
	if x != nil {
		return x.Download
	}
	return nil
}

type ApkPureApplicationDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpiryDate string `protobuf:"bytes,1,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sha1       string `protobuf:"bytes,3,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Size       int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	TorrentUrl string `protobuf:"bytes,6,opt,name=torrentUrl,proto3" json:"torrentUrl,omitempty"`
	TrackerUrl string `protobuf:"bytes,7,opt,name=trackerUrl,proto3" json:"trackerUrl,omitempty"`
	Type       string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Url        string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	ExpireData int64  `protobuf:"varint,12,opt,name=expireData,proto3" json:"expireData,omitempty"`
}

func (x *ApkPureApplicationDownload) Reset() {
	*x = ApkPureApplicationDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apkpure_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApkPureApplicationDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkPureApplicationDownload) ProtoMessage() {}

func (x *ApkPureApplicationDownload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apkpure_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkPureApplicationDownload.ProtoReflect.Descriptor instead.
func (*ApkPureApplicationDownload) Descriptor() ([]byte, []int) {
	return file_proto_apkpure_proto_rawDescGZIP(), []int{6}
}

func (x *ApkPureApplicationDownload) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ApkPureApplicationDownload) GetTorrentUrl() string {
	if x != nil {
		return x.TorrentUrl
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetTrackerUrl() string {
	if x != nil {
		return x.TrackerUrl
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ApkPureApplicationDownload) GetExpireData() int64 {
	if x != nil {
		return x.ExpireData
	}
	return 0
}

var File_proto_apkpure_proto protoreflect.FileDescriptor

var file_proto_apkpure_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x6b, 0x70, 0x75, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0f,
	0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x4b, 0x0a, 0x13, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x69, 0x0a, 0x15,
	0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x50, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72,
	0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x19, 0x41, 0x70, 0x6b, 0x50, 0x75,
	0x72, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x5a, 0x0a, 0x1e, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70,
	0x6b, 0x50, 0x75, 0x72, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xf8, 0x02, 0x0a, 0x1d, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x12, 0x3d, 0x0a,
	0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xfe, 0x01, 0x0a,
	0x1a, 0x41, 0x70, 0x6b, 0x50, 0x75, 0x72, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x68, 0x61, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x68, 0x61, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6b, 0x65,
	0x67, 0x75, 0x79, 0x73, 0x2f, 0x61, 0x70, 0x6b, 0x2d, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_apkpure_proto_rawDescOnce sync.Once
	file_proto_apkpure_proto_rawDescData = file_proto_apkpure_proto_rawDesc
)

func file_proto_apkpure_proto_rawDescGZIP() []byte {
	file_proto_apkpure_proto_rawDescOnce.Do(func() {
		file_proto_apkpure_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_apkpure_proto_rawDescData)
	})
	return file_proto_apkpure_proto_rawDescData
}

var file_proto_apkpure_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_apkpure_proto_goTypes = []any{
	(*ApkPureResponse)(nil),                // 0: proto.ApkPureResponse
	(*ApkPureResponseData)(nil),            // 1: proto.ApkPureResponseData
	(*ApkPureResponseDetail)(nil),          // 2: proto.ApkPureResponseDetail
	(*ApkPureApplicationVersion)(nil),      // 3: proto.ApkPureApplicationVersion
	(*ApkPureApplicationSearchResult)(nil), // 4: proto.ApkPureApplicationSearchResult
	(*ApkPureApplicationVersionData)(nil),  // 5: proto.ApkPureApplicationVersionData
	(*ApkPureApplicationDownload)(nil),     // 6: proto.ApkPureApplicationDownload
}
var file_proto_apkpure_proto_depIdxs = []int32{
	1, // 0: proto.ApkPureResponse.data:type_name -> proto.ApkPureResponseData
	2, // 1: proto.ApkPureResponseData.detail:type_name -> proto.ApkPureResponseDetail
	3, // 2: proto.ApkPureResponseDetail.applicationVersion:type_name -> proto.ApkPureApplicationVersion
	4, // 3: proto.ApkPureApplicationVersion.result:type_name -> proto.ApkPureApplicationSearchResult
	5, // 4: proto.ApkPureApplicationSearchResult.data:type_name -> proto.ApkPureApplicationVersionData
	6, // 5: proto.ApkPureApplicationVersionData.download:type_name -> proto.ApkPureApplicationDownload
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_apkpure_proto_init() }
func file_proto_apkpure_proto_init() {
	if File_proto_apkpure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_apkpure_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureResponseDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureApplicationVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureApplicationSearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureApplicationVersionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apkpure_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ApkPureApplicationDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_apkpure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_apkpure_proto_goTypes,
		DependencyIndexes: file_proto_apkpure_proto_depIdxs,
		MessageInfos:      file_proto_apkpure_proto_msgTypes,
	}.Build()
	File_proto_apkpure_proto = out.File
	file_proto_apkpure_proto_rawDesc = nil
	file_proto_apkpure_proto_goTypes = nil
	file_proto_apkpure_proto_depIdxs = nil
}
